from __future__ import annotations
import argparse, json, shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

def create_project(figure_id: str, name: str, figure_type: str, out_root: Path) -> Path:
    safe_id = figure_id.replace(".", "").replace(" ", "_")
    project = out_root / f"{safe_id}_{name}"
    for sub in ["source", "code", "editable", "final", "qa", "caption"]:
        (project / sub).mkdir(parents=True, exist_ok=True)
    template = ROOT / "shared" / "templates" / "figure_spec_template.json"
    data = json.loads(template.read_text(encoding="utf-8"))
    data["figure_id"] = figure_id
    data["short_name"] = name
    data["figure_type"] = figure_type
    (project / "figure_spec.json").write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    (project / "README.md").write_text(f"# {figure_id} {name}\n\nGenerated by journal-figure-skill-hub.\n", encoding="utf-8")
    (project / "caption" / "caption_draft.md").write_text(f"{figure_id}. Caption draft for {name}.\n", encoding="utf-8")
    (project / "caption" / "ai_disclosure.md").write_text("AI image generation used: no.\n", encoding="utf-8")
    return project

def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--figure-id", required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--type", required=True)
    p.add_argument("--out-root", default="figures")
    args = p.parse_args()
    project = create_project(args.figure_id, args.name, args.type, Path(args.out_root))
    print(project)

if __name__ == "__main__":
    main()
