colorblind_safe:
  - "#0072B2"
  - "#D55E00"
  - "#009E73"
  - "#CC79A7"
  - "#E69F00"
  - "#56B4E9"
  - "#F0E442"
  - "#000000"
sequential_thermal:
  - "#313695"
  - "#74add1"
  - "#ffffbf"
  - "#f46d43"
  - "#a50026"
